services:

  streamlit:
    build: ./src/app
    container_name: streamlit
    ports:
      - 8501:8501
    volumes:
      - ./src/app:/src/app

  openai:
    build: ./src/engine
    container_name: openai
    ports:
      - 80:80
    volumes:
      - ./src/engine:/src/engine
    env_file:
      - .env

  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.20.2
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    ports:
      - 8080:8080
    volumes:
      - ./data/weaviate:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'